import { business as b } from './config.js';
import './theme.css';
import { animateContent, setupMotion } from './motion.js';
import { vehicleIllustration } from './vehicles.js';
import { esc, icon, brand, map, truck } from './visuals.js';
const journeys = [
  {name:'Personal vehicles', short:'Everyday journeys', icon:'car', title:'Your day takes you places.', text:'The morning commute. A family visit. The long way home. Explore a clearer connection to the vehicle that takes you there.', label:'Family car', route:'Home → City → Home'},
  {name:'Motorcycles', short:'Life on two wheels', icon:'bike', title:'Every ride has a story.', text:'From neighborhood errands to the open road, explore tracking concepts built around the way you ride.', label:'Motorcycle', route:'Home → Pickup → Destination'},
  {name:'Business fleets', short:'Business in motion', icon:'truck', title:'Many vehicles. One perspective.', text:'Deliveries, service calls, and teams on the move. Discover how vehicle information can bring your daily operation into view.', label:'Delivery van', route:'Depot → Delivery → Return'}
];
const stations = [
  {title:'Understand the vehicle',text:'Every setup starts with the vehicle and its purpose. Compatibility, daily routes, and the information that matters shape the conversation.',detail:'Vehicle type · Usage · Tracking priorities',icon:'car'},
  {title:'Plan the installation',text:b.installation,detail:'Device suitability · Installation arrangements · Account setup',icon:'fence'},
  {title:'Bring the journey into view',text:'Learn how the agreed tracking features present vehicle activity, so the information has a practical place in your day.',detail:'Location views · Trip context · Getting familiar',icon:'route'}
];
document.querySelector('#app').innerHTML = `
<a class="skip" href="#main">Skip to content</a>
<header><div class="wrap header-inner">${brand()}<button class="menu-toggle" aria-label="Open navigation" aria-expanded="false" aria-controls="navigation">☰</button><nav id="navigation" aria-label="Main navigation"><a href="#solutions">Solutions</a><a href="#how-it-works">Our approach</a><a href="#about">Our story</a><a href="#faqs">FAQs</a><a class="button compact" href="#showcase">View Showcase ${icon('arrow')}</a></nav></div><div class="reading-progress"></div></header>
<main id="main"><section id="home" class="hero"><div class="wrap hero-top"><span class="eyebrow">GPS TRACKING / PHILIPPINES</span><span class="edition">A LITTLE CLOSER. EVERY MILE.</span></div><div class="wrap hero-grid"><div class="hero-copy"><h1>Every journey.<br>A connection<br><span>that stays.</span></h1><p>Life moves. Business moves. Stay connected to the vehicles that move your world.</p><a class="button" href="#solutions">Follow the journey ${icon('arrow')}</a><div class="tagline">${b.tagline}</div></div><div class="journey-poster"><span class="poster-label">THE JOURNEY, IN PERSPECTIVE</span><svg class="hero-road" viewBox="0 0 560 500" aria-hidden="true"><path d="M40 470V330Q40 270 110 270H405Q480 270 480 195V135Q480 65 410 65H270" fill="none" stroke="#d9dfd5" stroke-width="64"/><path id="hero-path" d="M40 470V330Q40 270 110 270H405Q480 270 480 195V135Q480 65 410 65H270" fill="none" stroke="#faf9f3" stroke-dasharray="8 12" stroke-width="2"/><path d="M40 470V330Q40 270 110 270H405Q480 270 480 195V135Q480 65 410 65H270" fill="none" stroke="#ff9d00" stroke-width="4"/><circle id="hero-marker" cx="40" cy="470" r="9" fill="#06234b" stroke="white" stroke-width="4"/></svg><div class="destination">${icon('pin')}<span>CONNECTED<br><strong>To what matters.</strong></span></div><div class="poster-truck">${truck}</div><div class="coordinate">14.5995° N &nbsp; 120.9842° E<br><span>Illustrative route · Not a live location</span></div><div class="poster-stamp">ON THE ROAD.<br><b>BY YOUR SIDE.</b></div></div></div><div class="wrap hero-bottom"><span>SCROLL TO EXPLORE ↓</span><span>PERSONAL VEHICLES <i>/</i> MOTORCYCLES <i>/</i> BUSINESS FLEETS</span><span>01 — 05</span></div></section>
<div class="route-nav" aria-label="Journey sections"><a href="#solutions"><span>01</span> Your journey</a><a href="#how-it-works"><span>02</span> Our approach</a><a href="#showcase"><span>03</span> In motion</a><a href="#features"><span>04</span> The details</a><a href="#about"><span>05</span> Our story</a></div>
<section id="solutions" class="section"><div class="wrap"><div class="section-head"><div><div class="eyebrow">01 / YOUR JOURNEY</div><h2>Different wheels.<br>Same connection.</h2></div><p>Choose your ride.<br>Explore a different point of view.</p></div><div class="vehicle-tabs" role="tablist" aria-label="Choose a vehicle">${journeys.map((j,i)=>`<button id="vehicle-tab-${i}" role="tab" aria-selected="${i===0}" aria-controls="vehicle-panel" tabindex="${i===0?0:-1}" data-vehicle="${i}">${icon(j.icon)}${j.name}<span>0${i+1}</span></button>`).join('')}</div><div id="vehicle-panel" role="tabpanel" aria-labelledby="vehicle-tab-0" tabindex="0"><div class="vehicle-scene"><div class="scene-sun"></div><div class="scene-road"></div><div id="vehicle-art"></div><span class="scene-caption">ORIGINAL ILLUSTRATION / EXPLORING POSSIBILITIES</span></div><div class="vehicle-copy"><div class="eyebrow" id="vehicle-kicker"></div><h3 id="vehicle-title"></h3><p id="vehicle-description"></p><div class="sample-route"><span>SAMPLE JOURNEY</span><strong id="vehicle-route"></strong></div><a class="text-link" href="#showcase">See a journey in motion ${icon('arrow')}</a></div></div></div></section>
<section id="how-it-works" class="section approach"><div class="wrap"><div class="section-head"><div><div class="eyebrow">02 / OUR APPROACH</div><h2>A thoughtful setup.<br>A clearer road ahead.</h2></div><p>Explore the stops along the way.<br>Select a marker to look closer.</p></div><div class="approach-layout"><div class="station-map"><svg viewBox="0 0 650 330" aria-hidden="true"><path d="M-20 280H160Q240 280 240 195V155Q240 75 320 75H690" fill="none" stroke="#e3e6dd" stroke-width="54"/><path d="M-20 280H160Q240 280 240 195V155Q240 75 320 75H690" fill="none" stroke="#ff9d00" stroke-width="3" stroke-dasharray="6 6"/></svg><span class="map-word word-one">THE START</span><span class="map-word word-two">A CLEARER VIEW</span>${stations.map((s,i)=>`<button class="station station-${i}" data-station="${i}" aria-pressed="${i===0}" aria-controls="station-detail" aria-label="Step ${i+1}: ${s.title}">${i+1}</button>`).join('')}<span class="map-note">PROCESS CONCEPT / NOT CUSTOMER LOCATIONS</span></div><article id="station-detail" aria-live="polite"></article></div><p class="note">${b.installationConfirmed ? 'Installation arrangements depend on the agreed setup.' : 'Draft process · Installation and onboarding arrangements require business confirmation.'}</p></div></section>
<section id="showcase" class="section tracking"><div class="wrap"><div class="section-head"><div><div class="eyebrow">03 / A JOURNEY IN MOTION</div><h2>Don’t just picture it.<br><span>Take it for a spin.</span></h2></div><p>Play a sample trip. Follow the route.<br>Discover what a little visibility can look like.</p></div><div class="demo-console"><div class="demo-top"><span>${icon('pin')} KA-TRACKER <b>/ JOURNEY EXPLORER</b></span><span class="demo-label">SIMULATION · SAMPLE DATA</span></div><div class="demo-grid"><div class="demo-map">${map('interactive')}<svg class="moving-layer" viewBox="0 0 700 460" aria-hidden="true"><path id="trip-path" d="M210 350 165 190 350 235 390 140 525 175 552 272" fill="none"/><g id="trip-marker"><circle r="21" fill="#06234b" opacity=".15"/><circle r="11" fill="#06234b" stroke="white" stroke-width="4"/></g></svg><span class="map-key"><i></i> Sample route <i></i> Simulated vehicle</span></div><aside class="trip-info"><span class="eyebrow">YOUR SAMPLE JOURNEY</span><h3 id="trip-vehicle">Family car</h3><span id="trip-state" role="status">Ready to explore</span><div class="trip-metrics"><div><small>TRIP PROGRESS</small><strong id="trip-percent">0<span>%</span></strong></div><div><small>SAMPLE DISTANCE</small><strong id="trip-distance">0.0<span> km</span></strong></div></div><label for="trip-progress">Explore the route</label><input id="trip-progress" type="range" min="0" max="100" value="0"><div class="trip-controls"><button class="button" id="play-trip">Play trip ▷</button><button id="reset-trip" aria-label="Reset trip">↺</button></div><p>Illustrative interaction only. This is not live tracking or confirmed KA-TRACKER software.</p></aside></div></div></div></section>
<section id="features" class="section"><div class="wrap"><div class="section-head"><div><div class="eyebrow">04 / THE DETAILS THAT MATTER</div><h2>Less wondering.<br>More understanding.</h2></div><p>Small pieces of information.<br>A more useful perspective.</p></div><div class="feature-list">${b.features.map((f,i)=>`<details><summary><span class="feature-number">0${i+1}</span>${icon(f.icon)}<h3>${esc(f.title)}</h3><span class="plus">+</span></summary><p>${esc(f.text)}</p></details>`).join('')}</div>${!b.featuresConfirmed ? '<p class="note">Proposed capabilities · Availability requires business confirmation.</p>' : ''}</div></section>
<section id="about" class="section about"><div class="wrap about-grid"><div class="logo-paper"><img src="${esc(b.logoUrl)}" alt="KA-TRACKER logo" width="360" height="360" loading="lazy"><span>KA-TRACKER / PHILIPPINES</span></div><div><div class="eyebrow">05 / OUR STORY</div><h2>More than a location.<br><span>A connection.</span></h2><p>A vehicle can carry a day’s work, a family’s plans, or the next chapter of a business. That’s why our focus starts with understanding the journey.</p><p>KA-TRACKER brings together clear communication, useful vehicle visibility, and a straightforward approach to getting started.</p><div class="signature">${b.tagline}</div>${b.email ? `<a class="text-link" href="mailto:${esc(b.email)}">${esc(b.email)} ${icon('arrow')}</a>` : ''}</div></div></section>
<section id="faqs" class="section"><div class="wrap faq-layout"><div><div class="eyebrow">BEFORE THE NEXT TURN</div><h2>A few things<br>you might wonder.</h2><p class="note">Draft answers · Business details require confirmation.</p></div><div>${b.faqs.map(([q,a])=>`<details><summary>${esc(q)}<span class="plus">+</span></summary><p>${esc(a)}</p></details>`).join('')}</div></div></section></main>
<footer><div class="wrap footer-top"><div class="eyebrow">WHEREVER THE ROAD TAKES YOU.</div><a href="#home">Kasama mo.<span>↑</span></a></div><div class="wrap footer-bottom">${brand()}<span>© ${new Date().getFullYear()} KA-TRACKER</span><button class="privacy-open">Privacy policy</button><a href="#solutions">Back to the journey ↗</a></div></footer><dialog id="privacy"><button class="dialog-close" aria-label="Close privacy policy">×</button><div class="eyebrow">DRAFT / BUSINESS REVIEW REQUIRED</div><h2>Privacy policy</h2><p>${esc(b.privacy)}</p></dialog>`;

const $ = s=>document.querySelector(s);
const menu=$('.menu-toggle'), nav=$('nav');
function closeMenu(){menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Open navigation');nav.classList.remove('open');}
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',open);menu.setAttribute('aria-label',open?'Close navigation':'Open navigation');nav.classList.toggle('open',open);});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('open')){closeMenu();menu.focus();}});
const privacy=$('#privacy');$('.privacy-open').onclick=()=>privacy.showModal();$('.dialog-close').onclick=()=>privacy.close();
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
let selected=0, progress=0, playing=false, previousTime=0, frame;
const path=$('#trip-path');
function drawTrip(){const point=path.getPointAtLength(path.getTotalLength()*progress/100);$('#trip-marker').setAttribute('transform',`translate(${point.x} ${point.y})`);$('#trip-progress').value=progress;$('#trip-percent').innerHTML=`${Math.round(progress)}<span>%</span>`;$('#trip-distance').innerHTML=`${(progress*.124).toFixed(1)}<span> km</span>`;}
function stopTrip(){playing=false;cancelAnimationFrame(frame);$('#play-trip').textContent=progress>=100?'Replay trip ↺':'Play trip ▷';$('#trip-state').textContent=progress>=100?'Sample journey complete':progress>0?'Paused · Sample trip':'Ready to explore';}
function tick(time){if(!playing)return;if(previousTime)progress=Math.min(100,progress+(time-previousTime)/180);previousTime=time;drawTrip();if(progress>=100){stopTrip();return;}frame=requestAnimationFrame(tick);}
$('#play-trip').onclick=()=>{if(playing){stopTrip();return;}if(progress>=100)progress=0;playing=true;previousTime=0;$('#play-trip').textContent='Pause trip Ⅱ';$('#trip-state').textContent='Playing · Sample trip';frame=requestAnimationFrame(tick);};
$('#reset-trip').onclick=()=>{progress=0;stopTrip();drawTrip();};
$('#trip-progress').addEventListener('input',e=>{progress=Number(e.target.value);stopTrip();drawTrip();});
document.addEventListener('visibilitychange',()=>{if(document.hidden)stopTrip();});
new IntersectionObserver(entries=>{if(!entries[0].isIntersecting&&playing)stopTrip();},{threshold:.1}).observe($('#showcase'));
function setVehicle(i){selected=i;const j=journeys[i];document.querySelectorAll('[data-vehicle]').forEach((button,n)=>{button.setAttribute('aria-selected',n===i);button.tabIndex=n===i?0:-1;});$('#vehicle-panel').setAttribute('aria-labelledby',`vehicle-tab-${i}`);$('#vehicle-kicker').textContent=j.short;$('#vehicle-title').textContent=j.title;$('#vehicle-description').textContent=j.text;$('#vehicle-route').textContent=j.route;$('#trip-vehicle').textContent=j.label;$('#vehicle-art').innerHTML=vehicleIllustration(j.icon);animateContent(document.querySelector('#vehicle-art'),document.querySelector('.vehicle-copy'));progress=0;stopTrip();drawTrip();}
document.querySelectorAll('[data-vehicle]').forEach(button=>{button.onclick=()=>setVehicle(Number(button.dataset.vehicle));button.onkeydown=e=>{let next;if(e.key==='ArrowRight')next=(selected+1)%3;if(e.key==='ArrowLeft')next=(selected+2)%3;if(e.key==='Home')next=0;if(e.key==='End')next=2;if(next!==undefined){e.preventDefault();setVehicle(next);$(`#vehicle-tab-${next}`).focus();}};});
function setStation(i){const s=stations[i];document.querySelectorAll('[data-station]').forEach((button,n)=>button.setAttribute('aria-pressed',n===i));$('#station-detail').innerHTML=`<span class="station-index">0${i+1} / THE APPROACH</span>${icon(s.icon)}<h3>${s.title}</h3><p>${esc(s.text)}</p><small>${s.detail}</small>`;}
document.querySelectorAll('[data-station]').forEach(button=>button.onclick=()=>{setStation(Number(button.dataset.station));animateContent(document.querySelector('#station-detail'));});setVehicle(0);setStation(0);
let scrollQueued=false;
function updateScroll(){const total=document.documentElement.scrollHeight-innerHeight;$('.reading-progress').style.width=`${total>0?scrollY/total*100:0}%`;if(!reduced.matches){const p=$('#hero-path');const point=p.getPointAtLength(p.getTotalLength()*Math.min(1,scrollY/600));$('#hero-marker').setAttribute('cx',point.x);$('#hero-marker').setAttribute('cy',point.y);}scrollQueued=false;}
addEventListener('scroll',()=>{if(!scrollQueued){scrollQueued=true;requestAnimationFrame(updateScroll);}},{passive:true});updateScroll();
const sectionsObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)document.querySelectorAll('.route-nav a').forEach(a=>{if(a.hash===`#${entry.target.id}`)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});}),{rootMargin:'-15% 0px -55% 0px'});['solutions','how-it-works','showcase','features','about'].forEach(id=>sectionsObserver.observe(document.getElementById(id)));
if(b.siteUrl){const canonical=document.createElement('link');canonical.rel='canonical';canonical.href=b.siteUrl;document.head.append(canonical);}

setupMotion();
